### ISSUE TITLE
Duclib crashes on Server Side

### ISSUE THREAD

**Issue by SlayDigger** [Lvgraef/DucLib#2]
Hey, ran into this issue trying to get my modpack to work on a server... Removing DucLib seemed to do just the trick. Trying to launch server would crash every single time and only just realized. Would be sick to have Recrafted Creatures on the server : ) https://mcpaste.io/9a8ac32691314bfe

**Comment by Lvgraef** [comment]
Thank you for reporting the issue 🙏

those are the logs but they do not seem to actually contain the crash? Do you also have a crash report in addition to these logs?

**Comment by Lvgraef** [comment]
Oh also, does this only happen on the server or also when you create a world which is not a server?

**Comment by SlayDigger** [comment]
This is only on the server, the mod worked fine clientside. I actually had to sift through all the mods like over and over to try and even find out what was creating it. I don't think that this was creating a crash report for some reason

**Comment by Lvgraef** [comment]
maybe it didn't because its a server, could you remove the obscureapi mod (and the mods that depend on it) temporarily, because i think that might be the issue. If it works after that then i can probably fix it

**Comment by Lvgraef** [comment]
Okay i found the issue i will lyk once its fixed

**Comment by Lvgraef** [comment]
I have fixed the issue, the new jar should be approved soon!
