### ISSUE TITLE
Crash when start the game(with duclib + recrafted creatures)

### ISSUE THREAD

**Issue by BradClc** [Lvgraef/DucLib#3]
Here is the crash report, it says there is a error in VertexBuffer.java .I don't konw what is it means.
[crash-2023-12-27_18.20.45-client.txt](https://github.com/Itskillerluc/DucLib/files/13777731/crash-2023-12-27_18.20.45-client.txt)
[crash-2023-12-27_18.11.58-client.txt](https://github.com/Itskillerluc/DucLib/files/13777739/crash-2023-12-27_18.11.58-client.txt)

**Comment by Lvgraef** [comment]
Wasn’t this only when using connector?

**Comment by BradClc** [comment]
I am not sure and I will try to run these two mods without connector later to give more information. To be honest, my modpack has around 200 forge mods and 10+ fabric mods with connector and they runs good until I put duclib and recrafted creatures in my modpack.

**Comment by BradClc** [comment]
Yes, you are right! When not using connector it runs really well.

**Comment by Lvgraef** [comment]
Yes, it is mentioned on the download page of connector that is experimental I believe. I don’t know the inner workings of connector, but I know an issue has been made for this on their GitHub already. I will see if I can get in touch with the dev.

**Comment by Lvgraef** [comment]
This has been fixed in the new connector update!
